# Generated by Django 4.2.15 on 2024-09-06 for Calibrix Ground Truth Export

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from uuid import uuid4


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calibrix_matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJobRecord',
            fields=[
                ('id', models.CharField(default=uuid4, max_length=36, primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('config', models.JSONField(help_text='Export configuration parameters')),
                ('priority', models.CharField(
                    choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')],
                    default='NORMAL',
                    max_length=10
                )),
                ('status', models.CharField(
                    choices=[
                        ('PENDING', 'Pending'),
                        ('IN_PROGRESS', 'In Progress'),
                        ('COMPLETED', 'Completed'),
                        ('FAILED', 'Failed'),
                        ('CANCELLED', 'Cancelled')
                    ],
                    default='PENDING',
                    max_length=15
                )),
                ('progress_percentage', models.IntegerField(default=0)),
                ('progress_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('export_paths', models.JSONField(blank=True, null=True)),
                ('total_detections_processed', models.IntegerField(blank=True, null=True)),
                ('rq_job_id', models.CharField(blank=True, max_length=36, null=True)),
                ('user', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'calibrix_matching_exportjobrecord',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exportjobrecord',
            index=models.Index(fields=['task_id', 'status'], name='calibrix_ma_task_id_b5b3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='exportjobrecord',
            index=models.Index(fields=['user', 'created_at'], name='calibrix_ma_user_id_0f5c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='exportjobrecord',
            index=models.Index(fields=['priority', 'status'], name='calibrix_ma_priority_6d4f9e_idx'),
        ),
    ]